### PR TITLE
Desc

### PR DESCRIPTION
**Pull request by jtsalisbury**
Made code less fugly. Added icon highlights. Added better saving. Added
better checks. Lots of menu improvements. Added ability for custom guns,
and icons. Much better overall.

### CODE REVIEW

**Comment by Exho1** [comment]
Well, guess I cant really call it mine anymore. You rewrote the entire thing :p

**Comment by jtsalisbury** [comment]
Lol yea you can. I want no credit for it. I was just improving the code and modifying things I saw fit. It is heavily based on your original code, I just changed - a lot

**Comment by Exho1** [comment]
I mean it doesnt feel right claiming credit, the codes almost all yours. But I will look through the code more in depth tomorrow, Iphones dont really like large walls of code

**Comment by jtsalisbury** [comment]
Well the code is honestly an entire rewrite of the serverside & shared stuff, with heavy modifications. I made the PR so that it is more efficient and has more of an ability to be customized. I spent a while redoing it since I was basing it off yours. You don't have to merge, but it would be bad not to, just don't mention me in the credits idc. You made the addon. You made the base. I just modified it. That's all :)

**Comment by jtsalisbury** [comment]
Btw I didn't really rewrite everything, a lot of the code was from yours, I just made new files and replaced the old which is why it seems like I rewrote everything

**Comment by Exho1** [comment]
Well thanks for doing this! I appreciate that you spent the time doing it. Theres a lot of good code examples in there that I can reference for future stuff which is always nice. The base for this was written in 2 hours so it really wasnt pretty lol

**Comment by jtsalisbury** [comment]
Also I didn't make this PR to make you feel bad or "claim ownership" I made it to honestly make the code better.

**Comment by Exho1** [comment]
Yeah I know you had good intentions. It just kinda caught me off guard how much was different (and better). I'm still pretty amateur with Lua as this shows, it aint pretty but it works.

**Comment by jtsalisbury** [comment]
Everyone has to start somewhere. It was a nice addon too for a first. Anyways, if you want to merge do it, if not you don't have to.

**Comment by Exho1** [comment]
I probably will after testing it! Then move on to finding another Coderhire addon to "clone", its actually a lot of fun.

**Comment by Exho1** [comment]
Eh, not sure so about some of it. The client menu seems really stretched vertically in my opinion and I liked how much the chat colors were colored. If you want, you could release that on the Workshop though you might want to redo the interface...

**Comment by jtsalisbury** [comment]
The menu "vertically" should be the same. I don't think I edited the size only the position. Also, your chat colors looked the same. I may just release it as my own, but I'd prefer for it to be one. And if you really care about the "size" which wasn't changed, that much, you can just make a new commit with it edited.

**Comment by jtsalisbury** [comment]
Just found this sitting here - this was a toxic PR from my end, I'm so sorry about this whole thing

**Pull request closed without merging**
